/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class proyectoJava.Programa */

#ifndef _Included_proyectoJava_Programa
#define _Included_proyectoJava_Programa

#ifdef __cplusplus
extern "C" {
#endif
/* Inaccessible static: _ready */
/*
 * Class:     proyectoJava.Programa
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_proyectoJava_Programa_getString (JNIEnv *, jobject);

JNIEXPORT int JNICALL Java_proyectoJava_Programa_addAtoB (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
